config/routes.rb
# encoding: utf-8
Dis::Application.routes.draw do
  # Авторизация редактора
  match '/auth/:provider/callback', to: 'sessions#create'
  match '/auth/failure',            to: 'sessions#failure'
  resource :session, only: :destroy

  # Работа с пользователями
  resources :users, only: [:index, :create, :update, :destroy] do
    collection do
      get :start
    end
    member do
      get  :auth
      post :request_auth
    end
  end

  # Вики-страницы
  match '/all.json', to: 'contents#all'

  root              via: :get,  to: 'contents#show',    defaults: { path: '' }
  root              via: :put,  to: 'contents#update',  defaults: { path: '' }
  match '/edit',                to: 'contents#edit',    defaults: { path: '' }
  match '/restore', via: :post, to: 'contents#restore', defaults: { path: '' }

  match '/*path/edit',                    to: 'contents#edit'
  match '/*path/restore',   via: :post,   to: 'contents#restore'
  match '/*path',           via: :get,    to: 'contents#show'
  match '/*path',           via: :put,    to: 'contents#update'
  match '/*path',           via: :delete, to: 'contents#destroy'
end

app/models/content.rb
# encoding: utf-8
# Модель (класс для работы с данными из базы данных) вики-страницы
class Content
  include Mongoid::Document

  field :path                   # Путь к вики-странице
  field :title                  # Кеш заголовка страницы. Берётся из текста.
  field :deleted_at, type: Time # Отметка, что страница удалена. Не удаляем её
                                # из БД, чтобы всегда можно было откатить
                                # удаление (что-то типа корзины).
  include Mongoid::Timestamps   # Добавляет поля created_at и updated_at,
                                # чтобы знать когда мы создали страницу,
                                # и когда последний раз изменили

  # Версии текста страницы. Там же хранятся авторы изменений.
  embeds_many :versions

  # Проверяем, что указали уникальный путь
  validates :path, presence: true, uniqueness: true

  # Создаём индексы, чтобы быстрее искать страницу по пути
  index :path, unique: true

  # Достаёт страницу (включая удалённые) по пути к ней. Если страницы с таким
  # путём нет, то выкинет ошибку 404.
  def self.by_path(path)
    content = self.where(path: path).first
    raise404 unless content
    content
  end

  # Возвращает страницы, которых не удалили
  def self.undeleted
    where(deleted_at: nil)
  end

  # Выкидывает ошибку 404 (Mongoid::Errors::DocumentNotFound)
  def self.raise404
    raise Mongoid::Errors::DocumentNotFound.new(self.class, [])
  end

  # Переместить в корзину
  def mark_as_deleted!
    self.deleted_at = Time.now
    self.save
  end

  # Восстановить из корзины
  def restore!
    self.deleted_at = nil
    self.save
  end

  # Была ли эта страница отмечена как удалённая
  def deleted?
    not self.deleted_at.nil?
  end

  # Возвращает нужную версию страницы. Если номер версии не передан,
  # то возвращает последнюю версию. Если указанной версии нет, то выкидывает
  # ошибку 404.
  def version(number = nil)
    version = number ? self.versions[number.to_i - 1] : self.versions.last
    self.class.raise404 unless version
    version
  end

  # Возвращает true для главной страницы (у которой адрес /)
  def root?
    '/' == self.path
  end

  # Создаёт новую версию текста страницы и обновляет кеш заголовка
  def update_text!(text, author = nil)
    return if not self.versions.empty? and self.versions.last.text == text
    version = self.versions.create(text: text, author: author)
    self.updated_at = Time.now.utc
    self.title = version.title
    self.save!
  end

  # В JSON-виде отдаём только заголовок и путь
  def as_json(options = { })
    { path: self.path, title: (root? ? 'Главная страница' : self.title) }
  end

  # Возвращает HTML-класс на основе path, чтобы выставить его в <article> и
  # выставлять стили специфичные для определённой страницы.
  def html_class
    root? ? 'root' : path.gsub(/^\//, '').gsub('/', '-').gsub('.', '')
  end

  # Читает HAML-код фильтра. Вынесено из метода filter в отдельный метод для
  # удобства тестирования.
  def filter_haml
    @filter ||= begin
      path = Rails.root.join("app/filters/#{self.html_class}.haml")
      return :no unless File.exists? path
      Haml::Engine.new(File.read(path))
    end
  end

  # Если для страницы есть фильтр, то он использует его, чтобы добавить
  # дополнительную вёрстку.
  def filter(html, bindings)
    unless :no == self.filter_haml
      doc = Nokogiri::HTML(html)
      html = self.filter_haml.render(bindings, html: doc)
    end
    html
  end
end

app/controllers/contents_controller.rb
# encoding: utf-8
# Вики-страницы
class ContentsController < ApplicationController
  # Запрещаем редактирование и удаление страниц посторонним посетителям
  before_filter :authenticate_user!, except: [:show, :all]

  # Добавляем в самое начала параметра path ведущий /
  before_filter :fix_path, except: :all

  # Загружаем страницу из БД для действий, где она нужна
  before_filter :load_content, only: [:show, :destroy, :restore]

  # Загружаем страницу из БД или создаём новую
  before_filter :load_or_initialize_content, only: [:edit, :update]

  # Отображение вики-страниц
  def show
    # Ищем страницу по текущему пути. Если страницу не будет найдена, то будет
    # выброшена ошибка 404 (Mongoid::Errors::DocumentNotFound).
    Content.raise404 if @content.deleted?
    @version = @content.version(params[:version])
  end

  # Страница редактирования
  def edit
  end

  # Сохраняем вики-страницу
  def update
    @content.update_text! params[:text], current_user
    redirect_to @content.path
  end

  # Удаляем вики-страницу
  def destroy
    # Не удаляем, а только помечаем страницу к удалению.
    # Так её всегда можно будет восстановить «из корзины».
    @content.mark_as_deleted!
    flash[:notice] = "Страница #{@content.path} была помещена в корзину"
    redirect_to @content.path
  end

  # Восстановление страницы после удаления
  def restore
    @content.restore!
    redirect_to @content.path
  end

  # Список всех вики-страниц сайта
  def all
    @all = Content.undeleted.order_by(title: :asc)
    render json: @all
  end

  private

  # Добавляем в path вперёд /, если его там нет.
  # Используется как фильтр, перед всеми действиями.
  def fix_path
    params[:path] = '/' + params[:path] unless params[:path].start_with? '/'
  end

  # Загружаем страницу из БД. Используется как фильтр, перед нужными
  # действиями.
  def load_content
    @content = Content.by_path(params[:path])
  end

  # Загружаем страницу из БД. Если такой страницы ещё нет, то создаём её.
  # Используется как фильтр, перед нужными действиями.
  def load_or_initialize_content
    @content = Content.find_or_initialize_by(path: params[:path])
  end
end

app/views/contents/edit.html.haml
- if @content.root?
  - title "Правка — Главная"
- else
  - title "Правка — #{@content.title || @content.path}"

%article.page.edit-content
  %h1
    Изменение
    - if @content.root?
      главной страницы
    - else
      страницы
      - if @content.title
        «<a href="#{@content.path}">#{@content.title}</a>»

  = form_tag @content.path, method: :put do
    %textarea( name="text" role="content-textarea" )= @content.versions.last.try(:text)

- content_for :controls do
  .page-controls.edit-content
    = button('Сохранить', role: 'save-content')
    .cancel
      %a{ href: @content.path } Отмена

app/views/contents/show.html.haml
- title @version.title if @version.title

- content_for :head do
  - if @version.keywords
    %meta{ name: 'keywords', content: @version.keywords }
  - if @version.description
    %meta{ name: 'description', content: @version.description }

%article.page{ class: @content.html_class }
  %h1
    = @version.title
    - unless @version.last?
      .old старая версия
  = @content.filter(@version.html, self).html_safe

- if signed_in?
  - content_for :controls do
    .page-controls
      = shadowed_button('Изменить', href: edit_content_path(@content))

      - unless @content.root?
        = form_tag @content.path, method: :delete, class: 'delete-content' do
          = shadowed_button('Удалить', role: 'submit')

      .history
        %h2 История ↓
        %ol
          - @content.versions.reverse_each do |i|
            %li{ class_if('current', @version == i), class_if('last', i.last?) }
              .number #{i.version}.
              %a{ href: i.last? ? request.path : "?version=#{i.version}" }
                = l i.created_at, :human
              %span.author= i.author.title