config/routes.rb
# encoding: utf-8
Dis::Application.routes.draw do
  # Авторизация редактора
  match '/auth/:provider/callback', to: 'sessions#create'
  match '/auth/failure',            to: 'sessions#failure'
  resource :session, only: :destroy

  # Работа с пользователями
  resources :users, only: [:index, :create, :update, :destroy] do
    collection do
      get :start
    end
    member do
      get  :auth
      post :request_auth
    end
  end

  # Вики-страницы
  match '/all.json', to: 'contents#all'

  root              via: :get,  to: 'contents#show',    defaults: { path: '' }
  root              via: :put,  to: 'contents#update',  defaults: { path: '' }
  match '/edit',                to: 'contents#edit',    defaults: { path: '' }
  match '/restore', via: :post, to: 'contents#restore', defaults: { path: '' }

  match '/*path/edit',                    to: 'contents#edit'
  match '/*path/restore',   via: :post,   to: 'contents#restore'
  match '/*path',           via: :get,    to: 'contents#show'
  match '/*path',           via: :put,    to: 'contents#update'
  match '/*path',           via: :delete, to: 'contents#destroy'
end

app/models/user.rb
# encoding: utf-8
# Модель (класс для работы с данными из базы данных) редактора, который может
# изменять тексты на сайте
class User
  include Mongoid::Document

  field :name                   # Имя редактора
  field :email                  # Эл. почта редактора
  field :role                   # Сфера деятельности редактора.
  field :auth_provider          # Сервис, с помощью котого пользователь входит на
                                # сайт (например, с помощью аккаунта Google)
  field :auth_uid               # ID пользователя в сервисе, с помощью которого
                                # пользователь входит на сайт
  field :reset_auth_token       # Случайная строка, чтобы пользователь мог
                                # изменить свои auth_provider и auth_uid
  field :session_token          # Случайная строка, которую мы записываем в
                                # сессию, чтобы знать, что пользователь уже
                                # вошёл на сайт. Как бы «пароль» от сайта
  field :deleted_at, type: Time # Отметка, что пользователь удалён. Не удаляем
                                # из пользователя из БД, чтобы отображать его
                                # в истории правок страницы
  field :signin_at, type: Time  # Когда пользователь последний раз входил на сайт
  include Mongoid::Timestamps   # Добавляет поля created_at и updated_at,
                                # чтобы знать когда мы создали пользователя,
                                # и когда последний раз изменили

  # Версии страниц, которые он редактировал
  has_many :contents

  # Проверяем, что эл. почту указали, указали правиль, и что она уникальна
  validates :email, presence: true, email: true, uniqueness: true

  # Во время создания пользователя генерируем токены
  after_create :generate_session_token!
  after_create :generate_reset_auth_token!

  # Создаём индексы, чтобы быстрее искать по каким-то полям
  index :session_token,              unique: true
  index [:auth_provider, :auth_uid], unique: true
  index :name

  # Возвращает редакторов, которых не удалили
  def self.undeleted
    where(deleted_at: nil)
  end

  # Если пользователь с такой эл. почтой уже есть в БД и был просто помечен, как
  # удалённый, то не создаём нового, а возвращаем старого пользователя.
  def self.new_or_restore(email)
    user = User.where(email: email).first
    if user
      user.deleted_at = nil
      user
    else
      User.new
    end
  end

  # Генерируемновый новый случайный session_token, по которому проверяем,
  # что пользователь уже вошёл на сайт
  def generate_session_token!
    self.session_token = SecureRandom.base64
    self.save!
  end

  # Генерирует новый случайный reset_auth_token, чтобы пользователь мог
  # доказать, что это он, ещё до того, как выставил auth_provider и auth_uid.
  def generate_reset_auth_token!
    self.reset_auth_token = SecureRandom.base64
    self.save!
  end

  # Открыл ли пользователь ссылку из пригласительно письма и выбрал ли способ
  # входа на сайт
  def confirmed?
    auth_uid and auth_provider
  end

  # Возвращает имя редактора или его эл. почту
  def title
    self.name || self.email
  end

  # Была ли редактор отмечена как удалённый
  def deleted?
    not self.deleted_at.nil?
  end

  # Если редактор не правил страницы (и нет версии, привязанной к нему), то
  # удаляем его, иначе — только помечаем, как удалённого.
  def destroy_or_mark_as_deleted!
    if Content.where('versions.author_id' => self.id).count.zero?
      self.destroy
    else
      self.deleted_at = Time.now
      self.save!
    end
  end
end

app/controllers/users_controller.rb
# encoding: utf-8
# Редакторы сайта
class UsersController < ApplicationController
  # Запрещаем все действия посторонним посетителям.
  # Кроме просмотра списка редакторов и выбора способа входа для новых
  # пользователей (которые пока ещё не могут войти).
  before_filter :authenticate_user!, except: :auth

  # Загружаем пользователя из БД для действий, где он нужен
  before_filter :load_user, only: [:update, :destroy, :request_auth, :auth]

  # Список всех редакторов
  def index
    @users = User.undeleted.order_by(name: :asc)
  end

  # Создаём нового пользователя и отправляем ему письмо с ссылкой, где он может
  # выбрать сервис авторизации
  def create
    user = User.new_or_restore(params[:user]['email'])
    if save_user(user)
      Mailer.welcome(current_user, user).deliver
      mail = user.email
      flash[:notice] = "Письмо с дальнешими инструкциями отправлено на #{mail}"
    end
    redirect_to users_path
  end

  # Изменение почты и имени редактора
  def update
    save_user(@user)
    redirect_to users_path
  end

  # Удаление редактора
  def destroy
    # Запрещаем редактору удалять самого себя
    if @user == current_user
      render text: "Нельзя удалить самого себя", status: :bad_request
      return
    end

    mail = @user.email
    @user.destroy_or_mark_as_deleted!
    flash[:notice] = "Пользователь #{mail} удалён"
    redirect_to users_path
  end

  # Просим пользователя сменить сервис авторизации (например, если он потерял
  # пароль от прошлого).
  def request_auth
    @user.generate_reset_auth_token!
    if current_user == @user
      # Если пользователь хочет сменить свой сервис авторизации, то сразу
      # перенаправляем его на страницу выбора нового
      redirect_to auth_user_path(@user, token: @user.reset_auth_token)
    else
      # Если сервис авторизации нужно сменить для другого пользователя, то
      # отправляем ему письмо
      Mailer.change_auth(current_user, @user).deliver
      mail = @user.email
      flash[:notice] = "Письмо с дальнешими инструкциями отправлено на #{mail}"
      redirect_to users_path
    end
  end

  # Пользователь выбирает сервис авторизации и свой auth_uid в этом сервисе
  def auth
    if params[:token].blank?
      render text: 'Не указан токен для смены авторизации', status: :bad_request
    elsif @user.reset_auth_token.blank?
      flash[:error] = 'Пользователь уже выбрал, как войти на сайт'
      redirect_to users_path
    elsif @user.reset_auth_token != params[:token]
      flash[:error] = 'Неправильный ключ для смены способа входа на сайт'
      redirect_to users_path
    else
      @no_signin_form = true
      session[:reset_auth_token] = params[:token]
    end
  end

  def start
    @show_signin = true
  end

  private

  # Сохраняет новую почту и имя редактора. Если произошли ошибки, то метод их
  # выводит и возврашает false.
  def save_user(user)
    user.name  = params[:user]['name']
    user.email = params[:user]['email']
    user.role  = params[:user]['role']
    if user.save
      true
    else
      # Если новые данные не проходят валидацию (например, почта пустая),
      # то выведем сообщение об ошибке
      flash[:error] = user.errors.full_messages
      false
    end
  end

  # Загружаем пользователя из БД. Используется как фильтр, перед нужными
  # действиями.
  def load_user
    @user = User.find(params[:id])
  end
end

app/views/users/auth.html.haml
- title 'Выбор способа входа'

%article.page.card.auth
  - if @user.confirmed?
    %h1 Смена способа входа

    %p Войдите в Google и выберите другую учётную запись:

    .methods
      = render 'shared/signin_methods'

    %p
      Если у вас нет учётной записи у Google, то скажите программистам какой
      сервис вам нужно добавить.

  - else
    %h1 Выберите способ входа

    %p
      Сайт кафедры сам не проверяет* ваш логин и пароль,
      поэтому мы просим другие сервисы проверить вашу личность.

    %p
      Перейдите на сайт Google, он вас вернёт обратно и сайт кафедры запомнит
      вашу учётную запись:

    .methods
      = render 'shared/signin_methods'

    %p
      Если у вас нет учётной записи у Google, то скажите программистам какой
      сервис вам нужно добавить.

    .notes
      * — потому что мало кто может сделать такую проверку
      по-настоящему безопасной, да и вы всё равно будете использовать один пароль
      на множестве сайтов.

app/views/users/index.html.haml
- title 'Редакторы'

%article.page.users
  %h1 Редакторы

  %ul
    - @users.each do |user|
      %li
        .edit
          = form_for user do |f|
            = f.email_field :email, placeholder: 'Эл. почта', required: true
            = f.text_field  :name,  placeholder: 'Имя'
            = f.text_field  :role,  placeholder: 'Сфера деятельности'
            = submit_button('Сохранить', role: 'save-user')
        .controls( role="user-controls" )
          = form_tag request_auth_user_path(user) do
            - if user.confirmed?
              - if user == current_user
                - title = 'Привязать к другому аккаунту'
              - else
                - title = 'Отправить письмо с ссылкой, чтобы привязать другой аккаунт'
              = submit_button('Сменить вход', title: title)
            - else
              = submit_button('Пригласить ещё раз', title: 'Повторно выслать приглашение, чтобы привязать аккаунт')
          - if user != current_user
            = form_for user, method: :delete do
              = shadowed_button('Удалить', role: 'delete-user')

  %h2 Новый пользователь
  = form_for User.new do |f|
    = f.email_field :email, placeholder: 'Эл. почта'
    = f.text_field  :name,  placeholder: 'Имя'
    = f.text_field  :role,  placeholder: 'Сфера деятельности'
    = submit_button('Пригласить')

app/views/users/start.html.haml
- title 'Первые шаги редактора'

- content_for :head do
  = stylesheet_link_tag    'start'
  = javascript_include_tag 'start'

%article.page.start
  %h1 Теперь вы редактор

  %ol
    %li( role="test-signin" )
      %p
        Чтобы потом войти на сайт дважды щёлкните справа от страницы
        (по серому полю) — появится форма.
      %p
        Попробуйте прямо сейчас →
    %li( role="test-exit" )
      %p
        Если вы работаете за чужим компьютером, то обязетельно выйдите с сайта,
        как закончите работу.
      %p
        Выход с сайта находится в правом верхнем углу рядом
        с вашим именем.
      %p
        Попробуйте прямо сейчас →
    %li
      Мы делаем самый лучший сайт кафедры, поэтому старайтесь писать
      качественный текст, который поможет посетителям сайта.

  .old-browser
    К сожалению, вы используете устарвеший браузер — вы не сможете с ним
    комфортно изменять сайта. Скачайте, например,
    <a href="http://www.google.com/chrome?hl=ru">Google Chrome</a> или
    <a href="http://www.mozilla.com/ru/firefox/">Mozilla Firefox</a>.

- content_for(:controls_class) { 'signin' }
- content_for :controls do
  .hole
    .rotator
      .light
      .shadow
      .signin-help щёлк-щёлк
      .signin-form
        .test
          %h3
            Редакция
          .methods
            = render 'shared/signin_methods'
        .ok
          Всё правильно
          %div Вы молодец!